min_version = "2026.6.10"

[settings]
lockfile = true

[tools]
flutter = "3.47.2"
make = "4.4.1"
java = "temurin-17.0.19+10"
ruby = { version = "3.4.10", os = ["macos"] }
cocoapods = { version = "1.17.0", os = ["macos"] }
