name: example
description: UI kit example

publish_to: 'none'

version: 0.0.1


environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.32.0"


dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  ui:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
