name: example
description: UI kit example

publish_to: 'none'

version: 0.0.1


environment:
  sdk: '>=3.13.2 <4.0.0'
  flutter: ">=3.47.2"


dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any
  cross_file: ^0.3.5+4

  ui:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  vm_service: any

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/avatar.svg
