// Mocks generated by Mockito from annotations
// in flutter_template_name/test/src/util/test_util.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;
import 'dart:convert' as _i17;
import 'dart:io' as _i9;
import 'dart:typed_data' as _i18;
import 'dart:ui' as _i16;

import 'package:drift/backends.dart' as _i7;
import 'package:drift/drift.dart' as _i4;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i8;
import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:firebase_messaging/firebase_messaging.dart' as _i11;
import 'package:firebase_messaging_platform_interface/firebase_messaging_platform_interface.dart'
    as _i3;
import 'package:flutter/material.dart' as _i15;
import 'package:flutter/services.dart' as _i14;
import 'package:flutter_template_name/src/common/api_client/api_client.dart'
    as _i13;
import 'package:flutter_template_name/src/common/database/database.dart' as _i6;
import 'package:flutter_template_name/src/feature/authentication/data/authentication_repository.dart'
    as _i19;
import 'package:flutter_template_name/src/feature/authentication/model/sign_in_data.dart'
    as _i21;
import 'package:flutter_template_name/src/feature/authentication/model/user.dart'
    as _i20;
import 'package:flutter_template_name/src/feature/settings/data/mappers/app_settings_codec.dart'
    as _i26;
import 'package:flutter_template_name/src/feature/settings/data/mappers/user_preferences_codec.dart'
    as _i28;
import 'package:flutter_template_name/src/feature/settings/data/providers/app_settings_data_provider.dart'
    as _i25;
import 'package:flutter_template_name/src/feature/settings/data/providers/user_preferences_data_provider.dart'
    as _i27;
import 'package:flutter_template_name/src/feature/settings/data/settings_repository.dart'
    as _i22;
import 'package:flutter_template_name/src/feature/settings/model/app_settings.dart'
    as _i23;
import 'package:flutter_template_name/src/feature/settings/model/user_preferences.dart'
    as _i24;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:shared_preferences/shared_preferences.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationSettings_1 extends _i1.SmartFake
    implements _i3.NotificationSettings {
  _FakeNotificationSettings_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_2 extends _i1.SmartFake
    implements _i4.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResultSetImplementation_3<Tbl, Row> extends _i1.SmartFake
    implements _i4.ResultSetImplementation<Tbl, Row> {
  _FakeResultSetImplementation_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_4<FirstT extends _i4.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i4.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_5 extends _i1.SmartFake
    implements _i4.GenerationContext {
  _FakeGenerationContext_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_6<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_7<T1> extends _i1.SmartFake
    implements _i4.Selectable<T1> {
  _FakeSelectable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTableInfo_8<TableDsl extends _i4.Table, D1> extends _i1.SmartFake
    implements _i4.TableInfo<TableDsl, D1> {
  _FakeTableInfo_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrationStrategy_9 extends _i1.SmartFake
    implements _i4.MigrationStrategy {
  _FakeMigrationStrategy_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DatabaseManager_10 extends _i1.SmartFake
    implements _i6.$DatabaseManager {
  _Fake$DatabaseManager_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsTbl_11 extends _i1.SmartFake implements _i6.SettingsTbl {
  _FakeSettingsTbl_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTrigger_12 extends _i1.SmartFake implements _i4.Trigger {
  _FakeTrigger_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogTbl_13 extends _i1.SmartFake implements _i6.LogTbl {
  _FakeLogTbl_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIndex_14 extends _i1.SmartFake implements _i4.Index {
  _FakeIndex_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogPrefixTbl_15 extends _i1.SmartFake implements _i6.LogPrefixTbl {
  _FakeLogPrefixTbl_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCharacteristicTbl_16 extends _i1.SmartFake
    implements _i6.CharacteristicTbl {
  _FakeCharacteristicTbl_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKvTbl_17 extends _i1.SmartFake implements _i6.KvTbl {
  _FakeKvTbl_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_18 extends _i1.SmartFake
    implements _i4.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_19 extends _i1.SmartFake
    implements _i4.GeneratedDatabase {
  _FakeGeneratedDatabase_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_20 extends _i1.SmartFake
    implements _i4.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_21 extends _i1.SmartFake
    implements _i4.DatabaseConnection {
  _FakeDatabaseConnection_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_22 extends _i1.SmartFake implements _i7.QueryExecutor {
  _FakeQueryExecutor_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_23 extends _i1.SmartFake
    implements _i8.StreamQueryStore {
  _FakeStreamQueryStore_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_24 extends _i1.SmartFake implements _i4.Migrator {
  _FakeMigrator_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_25<T1 extends _i4.Table, D1> extends _i1.SmartFake
    implements _i4.InsertStatement<T1, D1> {
  _FakeInsertStatement_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_26<T extends _i4.Table, D> extends _i1.SmartFake
    implements _i4.UpdateStatement<T, D> {
  _FakeUpdateStatement_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_27<T1 extends _i4.HasResultSet, D>
    extends _i1.SmartFake
    implements _i4.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_28<Row> extends _i1.SmartFake
    implements _i4.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_29<T1 extends _i4.Table, D1> extends _i1.SmartFake
    implements _i4.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_30 extends _i1.SmartFake implements _i9.File {
  _FakeFile_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_31 extends _i1.SmartFake implements Uri {
  _FakeUri_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectory_32 extends _i1.SmartFake implements _i9.Directory {
  _FakeDirectory_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileSystemEntity_33 extends _i1.SmartFake
    implements _i9.FileSystemEntity {
  _FakeFileSystemEntity_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_34 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRandomAccessFile_35 extends _i1.SmartFake
    implements _i9.RandomAccessFile {
  _FakeRandomAccessFile_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSink_36 extends _i1.SmartFake implements _i9.IOSink {
  _FakeIOSink_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileStat_37 extends _i1.SmartFake implements _i9.FileStat {
  _FakeFileStat_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferencesAsync_38 extends _i1.SmartFake
    implements _i10.SharedPreferencesAsync {
  _FakeSharedPreferencesAsync_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseMessaging].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseMessaging extends _i1.Mock implements _i11.FirebaseMessaging {
  @override
  _i2.FirebaseApp get app => (super.noSuchMethod(
    Invocation.getter(#app),
    returnValue: _FakeFirebaseApp_0(this, Invocation.getter(#app)),
    returnValueForMissingStub: _FakeFirebaseApp_0(
      this,
      Invocation.getter(#app),
    ),
  ) as _i2.FirebaseApp);

  @override
  bool get isAutoInitEnabled => (super.noSuchMethod(
    Invocation.getter(#isAutoInitEnabled),
    returnValue: false,
    returnValueForMissingStub: false,
  ) as bool);

  @override
  _i5.Stream<String> get onTokenRefresh => (super.noSuchMethod(
    Invocation.getter(#onTokenRefresh),
    returnValue: _i5.Stream<String>.empty(),
    returnValueForMissingStub: _i5.Stream<String>.empty(),
  ) as _i5.Stream<String>);

  @override
  set app(_i2.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
    Invocation.getter(#pluginConstants),
    returnValue: <dynamic, dynamic>{},
    returnValueForMissingStub: <dynamic, dynamic>{},
  ) as Map<dynamic, dynamic>);

  @override
  _i5.Future<_i3.RemoteMessage?> getInitialMessage() => (super.noSuchMethod(
    Invocation.method(#getInitialMessage, []),
    returnValue: _i5.Future<_i3.RemoteMessage?>.value(),
    returnValueForMissingStub: _i5.Future<_i3.RemoteMessage?>.value(),
  ) as _i5.Future<_i3.RemoteMessage?>);

  @override
  _i5.Future<void> deleteToken() => (super.noSuchMethod(
    Invocation.method(#deleteToken, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getAPNSToken() => (super.noSuchMethod(
    Invocation.method(#getAPNSToken, []),
    returnValue: _i5.Future<String?>.value(),
    returnValueForMissingStub: _i5.Future<String?>.value(),
  ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getToken({
    String? vapidKey,
    String? serviceWorkerScriptPath,
  }) => (super.noSuchMethod(
    Invocation.method(#getToken, [], {
      #vapidKey: vapidKey,
      #serviceWorkerScriptPath: serviceWorkerScriptPath,
    }),
    returnValue: _i5.Future<String?>.value(),
    returnValueForMissingStub: _i5.Future<String?>.value(),
  ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> isSupported() => (super.noSuchMethod(
    Invocation.method(#isSupported, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.NotificationSettings> getNotificationSettings() =>
      (super.noSuchMethod(
        Invocation.method(#getNotificationSettings, []),
        returnValue: _i5.Future<_i3.NotificationSettings>.value(
          _FakeNotificationSettings_1(
            this,
            Invocation.method(#getNotificationSettings, []),
          ),
        ),
        returnValueForMissingStub: _i5.Future<_i3.NotificationSettings>.value(
          _FakeNotificationSettings_1(
            this,
            Invocation.method(#getNotificationSettings, []),
          ),
        ),
      ) as _i5.Future<_i3.NotificationSettings>);

  @override
  _i5.Future<_i3.NotificationSettings> requestPermission({
    bool? alert = true,
    bool? announcement = false,
    bool? badge = true,
    bool? carPlay = false,
    bool? criticalAlert = false,
    bool? provisional = false,
    bool? sound = true,
    bool? providesAppNotificationSettings = false,
  }) => (super.noSuchMethod(
    Invocation.method(#requestPermission, [], {
      #alert: alert,
      #announcement: announcement,
      #badge: badge,
      #carPlay: carPlay,
      #criticalAlert: criticalAlert,
      #provisional: provisional,
      #sound: sound,
      #providesAppNotificationSettings: providesAppNotificationSettings,
    }),
    returnValue: _i5.Future<_i3.NotificationSettings>.value(
      _FakeNotificationSettings_1(
        this,
        Invocation.method(#requestPermission, [], {
          #alert: alert,
          #announcement: announcement,
          #badge: badge,
          #carPlay: carPlay,
          #criticalAlert: criticalAlert,
          #provisional: provisional,
          #sound: sound,
          #providesAppNotificationSettings: providesAppNotificationSettings,
        }),
      ),
    ),
    returnValueForMissingStub: _i5.Future<_i3.NotificationSettings>.value(
      _FakeNotificationSettings_1(
        this,
        Invocation.method(#requestPermission, [], {
          #alert: alert,
          #announcement: announcement,
          #badge: badge,
          #carPlay: carPlay,
          #criticalAlert: criticalAlert,
          #provisional: provisional,
          #sound: sound,
          #providesAppNotificationSettings: providesAppNotificationSettings,
        }),
      ),
    ),
  ) as _i5.Future<_i3.NotificationSettings>);

  @override
  _i5.Future<void> setAutoInitEnabled(bool? enabled) => (super.noSuchMethod(
    Invocation.method(#setAutoInitEnabled, [enabled]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setDeliveryMetricsExportToBigQuery(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(#setDeliveryMetricsExportToBigQuery, [enabled]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setForegroundNotificationPresentationOptions({
    bool? alert = false,
    bool? badge = false,
    bool? sound = false,
  }) => (super.noSuchMethod(
    Invocation.method(#setForegroundNotificationPresentationOptions, [], {
      #alert: alert,
      #badge: badge,
      #sound: sound,
    }),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> subscribeToTopic(String? topic) => (super.noSuchMethod(
    Invocation.method(#subscribeToTopic, [topic]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> unsubscribeFromTopic(String? topic) => (super.noSuchMethod(
    Invocation.method(#unsubscribeFromTopic, [topic]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);
}

/// A class which mocks [SharedPreferencesAsync].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesAsync extends _i1.Mock
    implements _i10.SharedPreferencesAsync {
  @override
  _i5.Future<Set<String>> getKeys({Set<String>? allowList}) =>
      (super.noSuchMethod(
        Invocation.method(#getKeys, [], {#allowList: allowList}),
        returnValue: _i5.Future<Set<String>>.value(<String>{}),
        returnValueForMissingStub: _i5.Future<Set<String>>.value(<String>{}),
      ) as _i5.Future<Set<String>>);

  @override
  _i5.Future<Map<String, Object?>> getAll({Set<String>? allowList}) =>
      (super.noSuchMethod(
        Invocation.method(#getAll, [], {#allowList: allowList}),
        returnValue: _i5.Future<Map<String, Object?>>.value(
          <String, Object?>{},
        ),
        returnValueForMissingStub: _i5.Future<Map<String, Object?>>.value(
          <String, Object?>{},
        ),
      ) as _i5.Future<Map<String, Object?>>);

  @override
  _i5.Future<bool?> getBool(String? key) => (super.noSuchMethod(
    Invocation.method(#getBool, [key]),
    returnValue: _i5.Future<bool?>.value(),
    returnValueForMissingStub: _i5.Future<bool?>.value(),
  ) as _i5.Future<bool?>);

  @override
  _i5.Future<int?> getInt(String? key) => (super.noSuchMethod(
    Invocation.method(#getInt, [key]),
    returnValue: _i5.Future<int?>.value(),
    returnValueForMissingStub: _i5.Future<int?>.value(),
  ) as _i5.Future<int?>);

  @override
  _i5.Future<double?> getDouble(String? key) => (super.noSuchMethod(
    Invocation.method(#getDouble, [key]),
    returnValue: _i5.Future<double?>.value(),
    returnValueForMissingStub: _i5.Future<double?>.value(),
  ) as _i5.Future<double?>);

  @override
  _i5.Future<String?> getString(String? key) => (super.noSuchMethod(
    Invocation.method(#getString, [key]),
    returnValue: _i5.Future<String?>.value(),
    returnValueForMissingStub: _i5.Future<String?>.value(),
  ) as _i5.Future<String?>);

  @override
  _i5.Future<List<String>?> getStringList(String? key) => (super.noSuchMethod(
    Invocation.method(#getStringList, [key]),
    returnValue: _i5.Future<List<String>?>.value(),
    returnValueForMissingStub: _i5.Future<List<String>?>.value(),
  ) as _i5.Future<List<String>?>);

  @override
  _i5.Future<bool> containsKey(String? key) => (super.noSuchMethod(
    Invocation.method(#containsKey, [key]),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setBool(String? key, bool? value) => (super.noSuchMethod(
    Invocation.method(#setBool, [key, value]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setInt(String? key, int? value) => (super.noSuchMethod(
    Invocation.method(#setInt, [key, value]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setDouble(String? key, double? value) => (super.noSuchMethod(
    Invocation.method(#setDouble, [key, value]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setString(String? key, String? value) => (super.noSuchMethod(
    Invocation.method(#setString, [key, value]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
        Invocation.method(#setStringList, [key, value]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> remove(String? key) => (super.noSuchMethod(
    Invocation.method(#remove, [key]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> clear({Set<String>? allowList}) => (super.noSuchMethod(
    Invocation.method(#clear, [], {#allowList: allowList}),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);
}

/// A class which mocks [SimpleSelectStatement].
///
/// See the documentation for Mockito's code generation for more information.
class MockSimpleSelectStatement<T extends _i4.HasResultSet, D> extends _i1.Mock
    implements _i4.SimpleSelectStatement<T, D> {
  @override
  bool get distinct => (super.noSuchMethod(
    Invocation.getter(#distinct),
    returnValue: false,
    returnValueForMissingStub: false,
  ) as bool);

  @override
  Set<_i4.ResultSetImplementation<dynamic, dynamic>> get watchedTables =>
      (super.noSuchMethod(
        Invocation.getter(#watchedTables),
        returnValue: <_i4.ResultSetImplementation<dynamic, dynamic>>{},
        returnValueForMissingStub:
            <_i4.ResultSetImplementation<dynamic, dynamic>>{},
      ) as Set<_i4.ResultSetImplementation<dynamic, dynamic>>);

  @override
  _i4.DatabaseConnectionUser get database => (super.noSuchMethod(
    Invocation.getter(#database),
    returnValue: _FakeDatabaseConnectionUser_2(
      this,
      Invocation.getter(#database),
    ),
    returnValueForMissingStub: _FakeDatabaseConnectionUser_2(
      this,
      Invocation.getter(#database),
    ),
  ) as _i4.DatabaseConnectionUser);

  @override
  _i4.ResultSetImplementation<T, D> get table => (super.noSuchMethod(
    Invocation.getter(#table),
    returnValue: _FakeResultSetImplementation_3<T, D>(
      this,
      Invocation.getter(#table),
    ),
    returnValueForMissingStub: _FakeResultSetImplementation_3<T, D>(
      this,
      Invocation.getter(#table),
    ),
  ) as _i4.ResultSetImplementation<T, D>);

  @override
  bool get writeReturningClause => (super.noSuchMethod(
    Invocation.getter(#writeReturningClause),
    returnValue: false,
    returnValueForMissingStub: false,
  ) as bool);

  @override
  set database(_i4.DatabaseConnectionUser? value) => super.noSuchMethod(
    Invocation.setter(#database, value),
    returnValueForMissingStub: null,
  );

  @override
  set table(_i4.ResultSetImplementation<T, D>? value) => super.noSuchMethod(
    Invocation.setter(#table, value),
    returnValueForMissingStub: null,
  );

  @override
  set whereExpr(_i4.Where? value) => super.noSuchMethod(
    Invocation.setter(#whereExpr, value),
    returnValueForMissingStub: null,
  );

  @override
  set orderByExpr(_i4.OrderBy? value) => super.noSuchMethod(
    Invocation.setter(#orderByExpr, value),
    returnValueForMissingStub: null,
  );

  @override
  set limitExpr(_i4.Limit? value) => super.noSuchMethod(
    Invocation.setter(#limitExpr, value),
    returnValueForMissingStub: null,
  );

  @override
  set writeReturningClause(bool? value) => super.noSuchMethod(
    Invocation.setter(#writeReturningClause, value),
    returnValueForMissingStub: null,
  );

  @override
  void writeStartPart(_i4.GenerationContext? ctx) => super.noSuchMethod(
    Invocation.method(#writeStartPart, [ctx]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<D>> get() => (super.noSuchMethod(
    Invocation.method(#get, []),
    returnValue: _i5.Future<List<D>>.value(<D>[]),
    returnValueForMissingStub: _i5.Future<List<D>>.value(<D>[]),
  ) as _i5.Future<List<D>>);

  @override
  _i5.Stream<List<D>> watch() => (super.noSuchMethod(
    Invocation.method(#watch, []),
    returnValue: _i5.Stream<List<D>>.empty(),
    returnValueForMissingStub: _i5.Stream<List<D>>.empty(),
  ) as _i5.Stream<List<D>>);

  @override
  _i4.JoinedSelectStatement<_i4.HasResultSet, dynamic> join(
    List<_i4.Join<_i4.HasResultSet, dynamic>>? joins,
  ) => (super.noSuchMethod(
    Invocation.method(#join, [joins]),
    returnValue: _FakeJoinedSelectStatement_4<_i4.HasResultSet, dynamic>(
      this,
      Invocation.method(#join, [joins]),
    ),
    returnValueForMissingStub:
        _FakeJoinedSelectStatement_4<_i4.HasResultSet, dynamic>(
          this,
          Invocation.method(#join, [joins]),
        ),
  ) as _i4.JoinedSelectStatement<_i4.HasResultSet, dynamic>);

  @override
  _i4.JoinedSelectStatement<_i4.HasResultSet, dynamic> addColumns(
    List<_i4.Expression<Object>>? expressions,
  ) => (super.noSuchMethod(
    Invocation.method(#addColumns, [expressions]),
    returnValue: _FakeJoinedSelectStatement_4<_i4.HasResultSet, dynamic>(
      this,
      Invocation.method(#addColumns, [expressions]),
    ),
    returnValueForMissingStub:
        _FakeJoinedSelectStatement_4<_i4.HasResultSet, dynamic>(
          this,
          Invocation.method(#addColumns, [expressions]),
        ),
  ) as _i4.JoinedSelectStatement<_i4.HasResultSet, dynamic>);

  @override
  void orderBy(List<_i4.OrderClauseGenerator<T>>? clauses) =>
      super.noSuchMethod(
        Invocation.method(#orderBy, [clauses]),
        returnValueForMissingStub: null,
      );

  @override
  void writeInto(_i4.GenerationContext? context) => super.noSuchMethod(
    Invocation.method(#writeInto, [context]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.GenerationContext constructQuery() => (super.noSuchMethod(
    Invocation.method(#constructQuery, []),
    returnValue: _FakeGenerationContext_5(
      this,
      Invocation.method(#constructQuery, []),
    ),
    returnValueForMissingStub: _FakeGenerationContext_5(
      this,
      Invocation.method(#constructQuery, []),
    ),
  ) as _i4.GenerationContext);

  @override
  void where(_i4.Expression<bool> Function(T)? filter) => super.noSuchMethod(
    Invocation.method(#where, [filter]),
    returnValueForMissingStub: null,
  );

  @override
  void limit(int? limit, {int? offset}) => super.noSuchMethod(
    Invocation.method(#limit, [limit], {#offset: offset}),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<D> getSingle() => (super.noSuchMethod(
    Invocation.method(#getSingle, []),
    returnValue:
        _i12.ifNotNull(
          _i12.dummyValueOrNull<D>(this, Invocation.method(#getSingle, [])),
          (D v) => _i5.Future<D>.value(v),
        ) ??
        _FakeFuture_6<D>(this, Invocation.method(#getSingle, [])),
    returnValueForMissingStub:
        _i12.ifNotNull(
          _i12.dummyValueOrNull<D>(this, Invocation.method(#getSingle, [])),
          (D v) => _i5.Future<D>.value(v),
        ) ??
        _FakeFuture_6<D>(this, Invocation.method(#getSingle, [])),
  ) as _i5.Future<D>);

  @override
  _i5.Stream<D> watchSingle() => (super.noSuchMethod(
    Invocation.method(#watchSingle, []),
    returnValue: _i5.Stream<D>.empty(),
    returnValueForMissingStub: _i5.Stream<D>.empty(),
  ) as _i5.Stream<D>);

  @override
  _i5.Future<D?> getSingleOrNull() => (super.noSuchMethod(
    Invocation.method(#getSingleOrNull, []),
    returnValue: _i5.Future<D?>.value(),
    returnValueForMissingStub: _i5.Future<D?>.value(),
  ) as _i5.Future<D?>);

  @override
  _i5.Stream<D?> watchSingleOrNull() => (super.noSuchMethod(
    Invocation.method(#watchSingleOrNull, []),
    returnValue: _i5.Stream<D?>.empty(),
    returnValueForMissingStub: _i5.Stream<D?>.empty(),
  ) as _i5.Stream<D?>);

  @override
  _i4.Selectable<N> map<N>(N Function(D)? mapper) => (super.noSuchMethod(
    Invocation.method(#map, [mapper]),
    returnValue: _FakeSelectable_7<N>(this, Invocation.method(#map, [mapper])),
    returnValueForMissingStub: _FakeSelectable_7<N>(
      this,
      Invocation.method(#map, [mapper]),
    ),
  ) as _i4.Selectable<N>);

  @override
  _i4.Selectable<N> asyncMap<N>(_i5.FutureOr<N> Function(D)? mapper) =>
      (super.noSuchMethod(
        Invocation.method(#asyncMap, [mapper]),
        returnValue: _FakeSelectable_7<N>(
          this,
          Invocation.method(#asyncMap, [mapper]),
        ),
        returnValueForMissingStub: _FakeSelectable_7<N>(
          this,
          Invocation.method(#asyncMap, [mapper]),
        ),
      ) as _i4.Selectable<N>);
}

/// A class which mocks [InsertStatement].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsertStatement<T extends _i4.Table, D> extends _i1.Mock
    implements _i4.InsertStatement<T, D> {
  @override
  _i4.DatabaseConnectionUser get database => (super.noSuchMethod(
    Invocation.getter(#database),
    returnValue: _FakeDatabaseConnectionUser_2(
      this,
      Invocation.getter(#database),
    ),
    returnValueForMissingStub: _FakeDatabaseConnectionUser_2(
      this,
      Invocation.getter(#database),
    ),
  ) as _i4.DatabaseConnectionUser);

  @override
  _i4.TableInfo<T, D> get table => (super.noSuchMethod(
    Invocation.getter(#table),
    returnValue: _FakeTableInfo_8<T, D>(this, Invocation.getter(#table)),
    returnValueForMissingStub: _FakeTableInfo_8<T, D>(
      this,
      Invocation.getter(#table),
    ),
  ) as _i4.TableInfo<T, D>);

  @override
  _i5.Future<int> insert(
    _i4.Insertable<D>? entity, {
    _i4.InsertMode? mode,
    _i4.UpsertClause<T, D>? onConflict,
  }) => (super.noSuchMethod(
    Invocation.method(
      #insert,
      [entity],
      {#mode: mode, #onConflict: onConflict},
    ),
    returnValue: _i5.Future<int>.value(0),
    returnValueForMissingStub: _i5.Future<int>.value(0),
  ) as _i5.Future<int>);

  @override
  _i5.Future<void> insertFromSelect(
    _i4.BaseSelectStatement<dynamic>? select, {
    required Map<_i4.Column<Object>, _i4.Expression<Object>>? columns,
    _i4.InsertMode? mode = _i4.InsertMode.insert,
    _i4.UpsertClause<T, D>? onConflict,
  }) => (super.noSuchMethod(
    Invocation.method(
      #insertFromSelect,
      [select],
      {#columns: columns, #mode: mode, #onConflict: onConflict},
    ),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<D> insertReturning(
    _i4.Insertable<D>? entity, {
    _i4.InsertMode? mode,
    _i4.UpsertClause<T, D>? onConflict,
  }) => (super.noSuchMethod(
    Invocation.method(
      #insertReturning,
      [entity],
      {#mode: mode, #onConflict: onConflict},
    ),
    returnValue:
        _i12.ifNotNull(
          _i12.dummyValueOrNull<D>(
            this,
            Invocation.method(
              #insertReturning,
              [entity],
              {#mode: mode, #onConflict: onConflict},
            ),
          ),
          (D v) => _i5.Future<D>.value(v),
        ) ??
        _FakeFuture_6<D>(
          this,
          Invocation.method(
            #insertReturning,
            [entity],
            {#mode: mode, #onConflict: onConflict},
          ),
        ),
    returnValueForMissingStub:
        _i12.ifNotNull(
          _i12.dummyValueOrNull<D>(
            this,
            Invocation.method(
              #insertReturning,
              [entity],
              {#mode: mode, #onConflict: onConflict},
            ),
          ),
          (D v) => _i5.Future<D>.value(v),
        ) ??
        _FakeFuture_6<D>(
          this,
          Invocation.method(
            #insertReturning,
            [entity],
            {#mode: mode, #onConflict: onConflict},
          ),
        ),
  ) as _i5.Future<D>);

  @override
  _i5.Future<D?> insertReturningOrNull(
    _i4.Insertable<D>? entity, {
    _i4.InsertMode? mode,
    _i4.UpsertClause<T, D>? onConflict,
  }) => (super.noSuchMethod(
    Invocation.method(
      #insertReturningOrNull,
      [entity],
      {#mode: mode, #onConflict: onConflict},
    ),
    returnValue: _i5.Future<D?>.value(),
    returnValueForMissingStub: _i5.Future<D?>.value(),
  ) as _i5.Future<D?>);

  @override
  _i5.Future<int> insertOnConflictUpdate(_i4.Insertable<D>? entity) =>
      (super.noSuchMethod(
        Invocation.method(#insertOnConflictUpdate, [entity]),
        returnValue: _i5.Future<int>.value(0),
        returnValueForMissingStub: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i4.GenerationContext createContext(
    _i4.Insertable<D>? entry,
    _i4.InsertMode? mode, {
    _i4.UpsertClause<T, D>? onConflict,
    bool? returning = false,
  }) => (super.noSuchMethod(
    Invocation.method(
      #createContext,
      [entry, mode],
      {#onConflict: onConflict, #returning: returning},
    ),
    returnValue: _FakeGenerationContext_5(
      this,
      Invocation.method(
        #createContext,
        [entry, mode],
        {#onConflict: onConflict, #returning: returning},
      ),
    ),
    returnValueForMissingStub: _FakeGenerationContext_5(
      this,
      Invocation.method(
        #createContext,
        [entry, mode],
        {#onConflict: onConflict, #returning: returning},
      ),
    ),
  ) as _i4.GenerationContext);

  @override
  _i4.GenerationContext createContextFromSelect(
    _i4.BaseSelectStatement<dynamic>? select,
    Map<_i4.Column<Object>, _i4.Expression<Object>>? columns,
    _i4.InsertMode? mode, {
    _i4.UpsertClause<T, D>? onConflict,
  }) => (super.noSuchMethod(
    Invocation.method(
      #createContextFromSelect,
      [select, columns, mode],
      {#onConflict: onConflict},
    ),
    returnValue: _FakeGenerationContext_5(
      this,
      Invocation.method(
        #createContextFromSelect,
        [select, columns, mode],
        {#onConflict: onConflict},
      ),
    ),
    returnValueForMissingStub: _FakeGenerationContext_5(
      this,
      Invocation.method(
        #createContextFromSelect,
        [select, columns, mode],
        {#onConflict: onConflict},
      ),
    ),
  ) as _i4.GenerationContext);

  @override
  void writeInsertable(
    _i4.GenerationContext? ctx,
    Map<String, _i4.Expression<Object>>? map,
  ) => super.noSuchMethod(
    Invocation.method(#writeInsertable, [ctx, map]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ApiClient$HTTP].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient$HTTP extends _i1.Mock implements _i13.ApiClient$HTTP {
  @override
  _i5.Future<_i13.ApiClient$HTTP$Response> get(
    String? path, {
    Map<String, Object?>? queryParameters,
    Map<String, Object?>? context,
    _i5.Future<void>? abortTrigger,
    Map<String, String>? headers,
  }) => (super.noSuchMethod(
    Invocation.method(
      #get,
      [path],
      {
        #queryParameters: queryParameters,
        #context: context,
        #abortTrigger: abortTrigger,
        #headers: headers,
      },
    ),
    returnValue: _i5.Future<_i13.ApiClient$HTTP$Response>.value(
      _i12.dummyValue<_i13.ApiClient$HTTP$Response>(
        this,
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #context: context,
            #abortTrigger: abortTrigger,
            #headers: headers,
          },
        ),
      ),
    ),
    returnValueForMissingStub: _i5.Future<_i13.ApiClient$HTTP$Response>.value(
      _i12.dummyValue<_i13.ApiClient$HTTP$Response>(
        this,
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #context: context,
            #abortTrigger: abortTrigger,
            #headers: headers,
          },
        ),
      ),
    ),
  ) as _i5.Future<_i13.ApiClient$HTTP$Response>);

  @override
  _i5.Future<_i13.ApiClient$HTTP$Response> post(
    String? path, {
    Map<String, Object?>? queryParameters,
    Map<String, String>? headers,
    Map<String, Object?>? context,
    _i5.Future<void>? abortTrigger,
    Map<String, Object?>? body,
    bool? multipart = false,
  }) => (super.noSuchMethod(
    Invocation.method(
      #post,
      [path],
      {
        #queryParameters: queryParameters,
        #headers: headers,
        #context: context,
        #abortTrigger: abortTrigger,
        #body: body,
        #multipart: multipart,
      },
    ),
    returnValue: _i5.Future<_i13.ApiClient$HTTP$Response>.value(
      _i12.dummyValue<_i13.ApiClient$HTTP$Response>(
        this,
        Invocation.method(
          #post,
          [path],
          {
            #queryParameters: queryParameters,
            #headers: headers,
            #context: context,
            #abortTrigger: abortTrigger,
            #body: body,
            #multipart: multipart,
          },
        ),
      ),
    ),
    returnValueForMissingStub: _i5.Future<_i13.ApiClient$HTTP$Response>.value(
      _i12.dummyValue<_i13.ApiClient$HTTP$Response>(
        this,
        Invocation.method(
          #post,
          [path],
          {
            #queryParameters: queryParameters,
            #headers: headers,
            #context: context,
            #abortTrigger: abortTrigger,
            #body: body,
            #multipart: multipart,
          },
        ),
      ),
    ),
  ) as _i5.Future<_i13.ApiClient$HTTP$Response>);

  @override
  _i5.Future<_i13.ApiClient$HTTP$Response> put(
    String? path, {
    Map<String, Object?>? queryParameters,
    Map<String, String>? headers,
    Map<String, Object?>? context,
    _i5.Future<void>? abortTrigger,
    Map<String, Object?>? body,
    bool? multipart = false,
  }) => (super.noSuchMethod(
    Invocation.method(
      #put,
      [path],
      {
        #queryParameters: queryParameters,
        #headers: headers,
        #context: context,
        #abortTrigger: abortTrigger,
        #body: body,
        #multipart: multipart,
      },
    ),
    returnValue: _i5.Future<_i13.ApiClient$HTTP$Response>.value(
      _i12.dummyValue<_i13.ApiClient$HTTP$Response>(
        this,
        Invocation.method(
          #put,
          [path],
          {
            #queryParameters: queryParameters,
            #headers: headers,
            #context: context,
            #abortTrigger: abortTrigger,
            #body: body,
            #multipart: multipart,
          },
        ),
      ),
    ),
    returnValueForMissingStub: _i5.Future<_i13.ApiClient$HTTP$Response>.value(
      _i12.dummyValue<_i13.ApiClient$HTTP$Response>(
        this,
        Invocation.method(
          #put,
          [path],
          {
            #queryParameters: queryParameters,
            #headers: headers,
            #context: context,
            #abortTrigger: abortTrigger,
            #body: body,
            #multipart: multipart,
          },
        ),
      ),
    ),
  ) as _i5.Future<_i13.ApiClient$HTTP$Response>);

  @override
  _i5.Future<_i13.ApiClient$HTTP$Response> delete(
    String? path, {
    Map<String, String>? headers,
    Map<String, Object?>? context,
    _i5.Future<void>? abortTrigger,
    Map<String, Object?>? body,
  }) => (super.noSuchMethod(
    Invocation.method(
      #delete,
      [path],
      {
        #headers: headers,
        #context: context,
        #abortTrigger: abortTrigger,
        #body: body,
      },
    ),
    returnValue: _i5.Future<_i13.ApiClient$HTTP$Response>.value(
      _i12.dummyValue<_i13.ApiClient$HTTP$Response>(
        this,
        Invocation.method(
          #delete,
          [path],
          {
            #headers: headers,
            #context: context,
            #abortTrigger: abortTrigger,
            #body: body,
          },
        ),
      ),
    ),
    returnValueForMissingStub: _i5.Future<_i13.ApiClient$HTTP$Response>.value(
      _i12.dummyValue<_i13.ApiClient$HTTP$Response>(
        this,
        Invocation.method(
          #delete,
          [path],
          {
            #headers: headers,
            #context: context,
            #abortTrigger: abortTrigger,
            #body: body,
          },
        ),
      ),
    ),
  ) as _i5.Future<_i13.ApiClient$HTTP$Response>);
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i6.Database {
  @override
  int get schemaVersion => (super.noSuchMethod(
    Invocation.getter(#schemaVersion),
    returnValue: 0,
    returnValueForMissingStub: 0,
  ) as int);

  @override
  _i4.MigrationStrategy get migration => (super.noSuchMethod(
    Invocation.getter(#migration),
    returnValue: _FakeMigrationStrategy_9(this, Invocation.getter(#migration)),
    returnValueForMissingStub: _FakeMigrationStrategy_9(
      this,
      Invocation.getter(#migration),
    ),
  ) as _i4.MigrationStrategy);

  @override
  _i6.$DatabaseManager get managers => (super.noSuchMethod(
    Invocation.getter(#managers),
    returnValue: _Fake$DatabaseManager_10(this, Invocation.getter(#managers)),
    returnValueForMissingStub: _Fake$DatabaseManager_10(
      this,
      Invocation.getter(#managers),
    ),
  ) as _i6.$DatabaseManager);

  @override
  _i6.SettingsTbl get settingsTbl => (super.noSuchMethod(
    Invocation.getter(#settingsTbl),
    returnValue: _FakeSettingsTbl_11(this, Invocation.getter(#settingsTbl)),
    returnValueForMissingStub: _FakeSettingsTbl_11(
      this,
      Invocation.getter(#settingsTbl),
    ),
  ) as _i6.SettingsTbl);

  @override
  _i4.Trigger get settingsMetaUpdatedAtTrig => (super.noSuchMethod(
    Invocation.getter(#settingsMetaUpdatedAtTrig),
    returnValue: _FakeTrigger_12(
      this,
      Invocation.getter(#settingsMetaUpdatedAtTrig),
    ),
    returnValueForMissingStub: _FakeTrigger_12(
      this,
      Invocation.getter(#settingsMetaUpdatedAtTrig),
    ),
  ) as _i4.Trigger);

  @override
  _i6.LogTbl get logTbl => (super.noSuchMethod(
    Invocation.getter(#logTbl),
    returnValue: _FakeLogTbl_13(this, Invocation.getter(#logTbl)),
    returnValueForMissingStub: _FakeLogTbl_13(this, Invocation.getter(#logTbl)),
  ) as _i6.LogTbl);

  @override
  _i4.Index get logTimeIdx => (super.noSuchMethod(
    Invocation.getter(#logTimeIdx),
    returnValue: _FakeIndex_14(this, Invocation.getter(#logTimeIdx)),
    returnValueForMissingStub: _FakeIndex_14(
      this,
      Invocation.getter(#logTimeIdx),
    ),
  ) as _i4.Index);

  @override
  _i4.Index get logLevelIdx => (super.noSuchMethod(
    Invocation.getter(#logLevelIdx),
    returnValue: _FakeIndex_14(this, Invocation.getter(#logLevelIdx)),
    returnValueForMissingStub: _FakeIndex_14(
      this,
      Invocation.getter(#logLevelIdx),
    ),
  ) as _i4.Index);

  @override
  _i6.LogPrefixTbl get logPrefixTbl => (super.noSuchMethod(
    Invocation.getter(#logPrefixTbl),
    returnValue: _FakeLogPrefixTbl_15(this, Invocation.getter(#logPrefixTbl)),
    returnValueForMissingStub: _FakeLogPrefixTbl_15(
      this,
      Invocation.getter(#logPrefixTbl),
    ),
  ) as _i6.LogPrefixTbl);

  @override
  _i4.Index get logPrefixPrefixIdx => (super.noSuchMethod(
    Invocation.getter(#logPrefixPrefixIdx),
    returnValue: _FakeIndex_14(this, Invocation.getter(#logPrefixPrefixIdx)),
    returnValueForMissingStub: _FakeIndex_14(
      this,
      Invocation.getter(#logPrefixPrefixIdx),
    ),
  ) as _i4.Index);

  @override
  _i4.Index get logPrefixLogIdIdx => (super.noSuchMethod(
    Invocation.getter(#logPrefixLogIdIdx),
    returnValue: _FakeIndex_14(this, Invocation.getter(#logPrefixLogIdIdx)),
    returnValueForMissingStub: _FakeIndex_14(
      this,
      Invocation.getter(#logPrefixLogIdIdx),
    ),
  ) as _i4.Index);

  @override
  _i4.Index get logPrefixLenIdx => (super.noSuchMethod(
    Invocation.getter(#logPrefixLenIdx),
    returnValue: _FakeIndex_14(this, Invocation.getter(#logPrefixLenIdx)),
    returnValueForMissingStub: _FakeIndex_14(
      this,
      Invocation.getter(#logPrefixLenIdx),
    ),
  ) as _i4.Index);

  @override
  _i6.CharacteristicTbl get characteristicTbl => (super.noSuchMethod(
    Invocation.getter(#characteristicTbl),
    returnValue: _FakeCharacteristicTbl_16(
      this,
      Invocation.getter(#characteristicTbl),
    ),
    returnValueForMissingStub: _FakeCharacteristicTbl_16(
      this,
      Invocation.getter(#characteristicTbl),
    ),
  ) as _i6.CharacteristicTbl);

  @override
  _i4.Index get characteristicMetaCreatedAtIdx => (super.noSuchMethod(
    Invocation.getter(#characteristicMetaCreatedAtIdx),
    returnValue: _FakeIndex_14(
      this,
      Invocation.getter(#characteristicMetaCreatedAtIdx),
    ),
    returnValueForMissingStub: _FakeIndex_14(
      this,
      Invocation.getter(#characteristicMetaCreatedAtIdx),
    ),
  ) as _i4.Index);

  @override
  _i4.Index get characteristicMetaUpdatedAtIdx => (super.noSuchMethod(
    Invocation.getter(#characteristicMetaUpdatedAtIdx),
    returnValue: _FakeIndex_14(
      this,
      Invocation.getter(#characteristicMetaUpdatedAtIdx),
    ),
    returnValueForMissingStub: _FakeIndex_14(
      this,
      Invocation.getter(#characteristicMetaUpdatedAtIdx),
    ),
  ) as _i4.Index);

  @override
  _i4.Trigger get characteristicMetaUpdatedAtTrig => (super.noSuchMethod(
    Invocation.getter(#characteristicMetaUpdatedAtTrig),
    returnValue: _FakeTrigger_12(
      this,
      Invocation.getter(#characteristicMetaUpdatedAtTrig),
    ),
    returnValueForMissingStub: _FakeTrigger_12(
      this,
      Invocation.getter(#characteristicMetaUpdatedAtTrig),
    ),
  ) as _i4.Trigger);

  @override
  _i6.KvTbl get kvTbl => (super.noSuchMethod(
    Invocation.getter(#kvTbl),
    returnValue: _FakeKvTbl_17(this, Invocation.getter(#kvTbl)),
    returnValueForMissingStub: _FakeKvTbl_17(this, Invocation.getter(#kvTbl)),
  ) as _i6.KvTbl);

  @override
  _i4.Index get kvMetaCreatedAtIdx => (super.noSuchMethod(
    Invocation.getter(#kvMetaCreatedAtIdx),
    returnValue: _FakeIndex_14(this, Invocation.getter(#kvMetaCreatedAtIdx)),
    returnValueForMissingStub: _FakeIndex_14(
      this,
      Invocation.getter(#kvMetaCreatedAtIdx),
    ),
  ) as _i4.Index);

  @override
  _i4.Index get kvMetaUpdatedAtIdx => (super.noSuchMethod(
    Invocation.getter(#kvMetaUpdatedAtIdx),
    returnValue: _FakeIndex_14(this, Invocation.getter(#kvMetaUpdatedAtIdx)),
    returnValueForMissingStub: _FakeIndex_14(
      this,
      Invocation.getter(#kvMetaUpdatedAtIdx),
    ),
  ) as _i4.Index);

  @override
  _i4.Trigger get kvMetaUpdatedAtTrig => (super.noSuchMethod(
    Invocation.getter(#kvMetaUpdatedAtTrig),
    returnValue: _FakeTrigger_12(this, Invocation.getter(#kvMetaUpdatedAtTrig)),
    returnValueForMissingStub: _FakeTrigger_12(
      this,
      Invocation.getter(#kvMetaUpdatedAtTrig),
    ),
  ) as _i4.Trigger);

  @override
  Iterable<_i4.TableInfo<_i4.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i4.TableInfo<_i4.Table, Object?>>[],
        returnValueForMissingStub: <_i4.TableInfo<_i4.Table, Object?>>[],
      ) as Iterable<_i4.TableInfo<_i4.Table, Object?>>);

  @override
  List<_i4.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
    Invocation.getter(#allSchemaEntities),
    returnValue: <_i4.DatabaseSchemaEntity>[],
    returnValueForMissingStub: <_i4.DatabaseSchemaEntity>[],
  ) as List<_i4.DatabaseSchemaEntity>);

  @override
  _i4.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
    Invocation.getter(#streamUpdateRules),
    returnValue: _FakeStreamQueryUpdateRules_18(
      this,
      Invocation.getter(#streamUpdateRules),
    ),
    returnValueForMissingStub: _FakeStreamQueryUpdateRules_18(
      this,
      Invocation.getter(#streamUpdateRules),
    ),
  ) as _i4.StreamQueryUpdateRules);

  @override
  _i4.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
    Invocation.getter(#attachedDatabase),
    returnValue: _FakeGeneratedDatabase_19(
      this,
      Invocation.getter(#attachedDatabase),
    ),
    returnValueForMissingStub: _FakeGeneratedDatabase_19(
      this,
      Invocation.getter(#attachedDatabase),
    ),
  ) as _i4.GeneratedDatabase);

  @override
  _i4.DriftDatabaseOptions get options => (super.noSuchMethod(
    Invocation.getter(#options),
    returnValue: _FakeDriftDatabaseOptions_20(
      this,
      Invocation.getter(#options),
    ),
    returnValueForMissingStub: _FakeDriftDatabaseOptions_20(
      this,
      Invocation.getter(#options),
    ),
  ) as _i4.DriftDatabaseOptions);

  @override
  _i4.DatabaseConnection get connection => (super.noSuchMethod(
    Invocation.getter(#connection),
    returnValue: _FakeDatabaseConnection_21(
      this,
      Invocation.getter(#connection),
    ),
    returnValueForMissingStub: _FakeDatabaseConnection_21(
      this,
      Invocation.getter(#connection),
    ),
  ) as _i4.DatabaseConnection);

  @override
  _i4.SqlTypes get typeMapping => (super.noSuchMethod(
    Invocation.getter(#typeMapping),
    returnValue: _i12.dummyValue<_i4.SqlTypes>(
      this,
      Invocation.getter(#typeMapping),
    ),
    returnValueForMissingStub: _i12.dummyValue<_i4.SqlTypes>(
      this,
      Invocation.getter(#typeMapping),
    ),
  ) as _i4.SqlTypes);

  @override
  _i7.QueryExecutor get executor => (super.noSuchMethod(
    Invocation.getter(#executor),
    returnValue: _FakeQueryExecutor_22(this, Invocation.getter(#executor)),
    returnValueForMissingStub: _FakeQueryExecutor_22(
      this,
      Invocation.getter(#executor),
    ),
  ) as _i7.QueryExecutor);

  @override
  _i8.StreamQueryStore get streamQueries => (super.noSuchMethod(
    Invocation.getter(#streamQueries),
    returnValue: _FakeStreamQueryStore_23(
      this,
      Invocation.getter(#streamQueries),
    ),
    returnValueForMissingStub: _FakeStreamQueryStore_23(
      this,
      Invocation.getter(#streamQueries),
    ),
  ) as _i8.StreamQueryStore);

  @override
  _i4.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
    Invocation.getter(#resolvedEngine),
    returnValue: _FakeDatabaseConnectionUser_2(
      this,
      Invocation.getter(#resolvedEngine),
    ),
    returnValueForMissingStub: _FakeDatabaseConnectionUser_2(
      this,
      Invocation.getter(#resolvedEngine),
    ),
  ) as _i4.DatabaseConnectionUser);

  @override
  _i4.Migrator createMigrator() => (super.noSuchMethod(
    Invocation.method(#createMigrator, []),
    returnValue: _FakeMigrator_24(this, Invocation.method(#createMigrator, [])),
    returnValueForMissingStub: _FakeMigrator_24(
      this,
      Invocation.method(#createMigrator, []),
    ),
  ) as _i4.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i7.QueryExecutor? executor,
    _i4.OpeningDetails? details,
  ) => (super.noSuchMethod(
    Invocation.method(#beforeOpen, [executor, details]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
    Invocation.method(#close, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<Ret> computeWithDatabase<Ret, DB extends _i4.GeneratedDatabase>({
    required _i5.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i4.DatabaseConnection)? connect,
  }) => (super.noSuchMethod(
    Invocation.method(#computeWithDatabase, [], {
      #computation: computation,
      #connect: connect,
    }),
    returnValue:
        _i12.ifNotNull(
          _i12.dummyValueOrNull<Ret>(
            this,
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
          ),
          (Ret v) => _i5.Future<Ret>.value(v),
        ) ??
        _FakeFuture_6<Ret>(
          this,
          Invocation.method(#computeWithDatabase, [], {
            #computation: computation,
            #connect: connect,
          }),
        ),
    returnValueForMissingStub:
        _i12.ifNotNull(
          _i12.dummyValueOrNull<Ret>(
            this,
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
          ),
          (Ret v) => _i5.Future<Ret>.value(v),
        ) ??
        _FakeFuture_6<Ret>(
          this,
          Invocation.method(#computeWithDatabase, [], {
            #computation: computation,
            #connect: connect,
          }),
        ),
  ) as _i5.Future<Ret>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
    _i8.QueryStreamFetcher<T>? stmt,
  ) => (super.noSuchMethod(
    Invocation.method(#createStream, [stmt]),
    returnValue: _i5.Stream<T>.empty(),
    returnValueForMissingStub: _i5.Stream<T>.empty(),
  ) as _i5.Stream<T>);

  @override
  T alias<T, D>(_i4.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
        Invocation.method(#alias, [table, alias]),
        returnValue: _i12.dummyValue<T>(
          this,
          Invocation.method(#alias, [table, alias]),
        ),
        returnValueForMissingStub: _i12.dummyValue<T>(
          this,
          Invocation.method(#alias, [table, alias]),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i4.TableInfo<_i4.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i4.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<Set<_i4.TableUpdate>> tableUpdates([
    _i4.TableUpdateQuery? query = const _i4.TableUpdateQuery.any(),
  ]) => (super.noSuchMethod(
    Invocation.method(#tableUpdates, [query]),
    returnValue: _i5.Stream<Set<_i4.TableUpdate>>.empty(),
    returnValueForMissingStub: _i5.Stream<Set<_i4.TableUpdate>>.empty(),
  ) as _i5.Stream<Set<_i4.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
    _i5.FutureOr<T> Function(_i7.QueryExecutor)? fn,
  ) => (super.noSuchMethod(
    Invocation.method(#doWhenOpened, [fn]),
    returnValue:
        _i12.ifNotNull(
          _i12.dummyValueOrNull<T>(
            this,
            Invocation.method(#doWhenOpened, [fn]),
          ),
          (T v) => _i5.Future<T>.value(v),
        ) ??
        _FakeFuture_6<T>(this, Invocation.method(#doWhenOpened, [fn])),
    returnValueForMissingStub:
        _i12.ifNotNull(
          _i12.dummyValueOrNull<T>(
            this,
            Invocation.method(#doWhenOpened, [fn]),
          ),
          (T v) => _i5.Future<T>.value(v),
        ) ??
        _FakeFuture_6<T>(this, Invocation.method(#doWhenOpened, [fn])),
  ) as _i5.Future<T>);

  @override
  _i4.InsertStatement<T, D> into<T extends _i4.Table, D>(
    _i4.TableInfo<T, D>? table,
  ) => (super.noSuchMethod(
    Invocation.method(#into, [table]),
    returnValue: _FakeInsertStatement_25<T, D>(
      this,
      Invocation.method(#into, [table]),
    ),
    returnValueForMissingStub: _FakeInsertStatement_25<T, D>(
      this,
      Invocation.method(#into, [table]),
    ),
  ) as _i4.InsertStatement<T, D>);

  @override
  _i4.UpdateStatement<Tbl, R> update<Tbl extends _i4.Table, R>(
    _i4.TableInfo<Tbl, R>? table,
  ) => (super.noSuchMethod(
    Invocation.method(#update, [table]),
    returnValue: _FakeUpdateStatement_26<Tbl, R>(
      this,
      Invocation.method(#update, [table]),
    ),
    returnValueForMissingStub: _FakeUpdateStatement_26<Tbl, R>(
      this,
      Invocation.method(#update, [table]),
    ),
  ) as _i4.UpdateStatement<Tbl, R>);

  @override
  _i4.SimpleSelectStatement<T, R> select<T extends _i4.HasResultSet, R>(
    _i4.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) => (super.noSuchMethod(
    Invocation.method(#select, [table], {#distinct: distinct}),
    returnValue: _FakeSimpleSelectStatement_27<T, R>(
      this,
      Invocation.method(#select, [table], {#distinct: distinct}),
    ),
    returnValueForMissingStub: _FakeSimpleSelectStatement_27<T, R>(
      this,
      Invocation.method(#select, [table], {#distinct: distinct}),
    ),
  ) as _i4.SimpleSelectStatement<T, R>);

  @override
  _i4.JoinedSelectStatement<T, R> selectOnly<T extends _i4.HasResultSet, R>(
    _i4.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) => (super.noSuchMethod(
    Invocation.method(#selectOnly, [table], {#distinct: distinct}),
    returnValue: _FakeJoinedSelectStatement_4<T, R>(
      this,
      Invocation.method(#selectOnly, [table], {#distinct: distinct}),
    ),
    returnValueForMissingStub: _FakeJoinedSelectStatement_4<T, R>(
      this,
      Invocation.method(#selectOnly, [table], {#distinct: distinct}),
    ),
  ) as _i4.JoinedSelectStatement<T, R>);

  @override
  _i4.BaseSelectStatement<_i4.TypedResult> selectExpressions(
    Iterable<_i4.Expression<Object>>? columns,
  ) => (super.noSuchMethod(
    Invocation.method(#selectExpressions, [columns]),
    returnValue: _FakeBaseSelectStatement_28<_i4.TypedResult>(
      this,
      Invocation.method(#selectExpressions, [columns]),
    ),
    returnValueForMissingStub: _FakeBaseSelectStatement_28<_i4.TypedResult>(
      this,
      Invocation.method(#selectExpressions, [columns]),
    ),
  ) as _i4.BaseSelectStatement<_i4.TypedResult>);

  @override
  _i4.DeleteStatement<T, D> delete<T extends _i4.Table, D>(
    _i4.TableInfo<T, D>? table,
  ) => (super.noSuchMethod(
    Invocation.method(#delete, [table]),
    returnValue: _FakeDeleteStatement_29<T, D>(
      this,
      Invocation.method(#delete, [table]),
    ),
    returnValueForMissingStub: _FakeDeleteStatement_29<T, D>(
      this,
      Invocation.method(#delete, [table]),
    ),
  ) as _i4.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i4.UpdateKind? updateKind,
  }) => (super.noSuchMethod(
    Invocation.method(
      #customUpdate,
      [query],
      {#variables: variables, #updates: updates, #updateKind: updateKind},
    ),
    returnValue: _i5.Future<int>.value(0),
    returnValueForMissingStub: _i5.Future<int>.value(0),
  ) as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) => (super.noSuchMethod(
    Invocation.method(
      #customInsert,
      [query],
      {#variables: variables, #updates: updates},
    ),
    returnValue: _i5.Future<int>.value(0),
    returnValueForMissingStub: _i5.Future<int>.value(0),
  ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i4.QueryRow>> customWriteReturning(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i4.UpdateKind? updateKind,
  }) => (super.noSuchMethod(
    Invocation.method(
      #customWriteReturning,
      [query],
      {#variables: variables, #updates: updates, #updateKind: updateKind},
    ),
    returnValue: _i5.Future<List<_i4.QueryRow>>.value(<_i4.QueryRow>[]),
    returnValueForMissingStub: _i5.Future<List<_i4.QueryRow>>.value(
      <_i4.QueryRow>[],
    ),
  ) as _i5.Future<List<_i4.QueryRow>>);

  @override
  _i4.Selectable<_i4.QueryRow> customSelect(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) => (super.noSuchMethod(
    Invocation.method(
      #customSelect,
      [query],
      {#variables: variables, #readsFrom: readsFrom},
    ),
    returnValue: _FakeSelectable_7<_i4.QueryRow>(
      this,
      Invocation.method(
        #customSelect,
        [query],
        {#variables: variables, #readsFrom: readsFrom},
      ),
    ),
    returnValueForMissingStub: _FakeSelectable_7<_i4.QueryRow>(
      this,
      Invocation.method(
        #customSelect,
        [query],
        {#variables: variables, #readsFrom: readsFrom},
      ),
    ),
  ) as _i4.Selectable<_i4.QueryRow>);

  @override
  _i4.Selectable<_i4.QueryRow> customSelectQuery(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) => (super.noSuchMethod(
    Invocation.method(
      #customSelectQuery,
      [query],
      {#variables: variables, #readsFrom: readsFrom},
    ),
    returnValue: _FakeSelectable_7<_i4.QueryRow>(
      this,
      Invocation.method(
        #customSelectQuery,
        [query],
        {#variables: variables, #readsFrom: readsFrom},
      ),
    ),
    returnValueForMissingStub: _FakeSelectable_7<_i4.QueryRow>(
      this,
      Invocation.method(
        #customSelectQuery,
        [query],
        {#variables: variables, #readsFrom: readsFrom},
      ),
    ),
  ) as _i4.Selectable<_i4.QueryRow>);

  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
        Invocation.method(#customStatement, [statement, args]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) => (super.noSuchMethod(
    Invocation.method(#transaction, [action], {#requireNew: requireNew}),
    returnValue:
        _i12.ifNotNull(
          _i12.dummyValueOrNull<T>(
            this,
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
          ),
          (T v) => _i5.Future<T>.value(v),
        ) ??
        _FakeFuture_6<T>(
          this,
          Invocation.method(#transaction, [action], {#requireNew: requireNew}),
        ),
    returnValueForMissingStub:
        _i12.ifNotNull(
          _i12.dummyValueOrNull<T>(
            this,
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
          ),
          (T v) => _i5.Future<T>.value(v),
        ) ??
        _FakeFuture_6<T>(
          this,
          Invocation.method(#transaction, [action], {#requireNew: requireNew}),
        ),
  ) as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(#exclusively, [action]),
        returnValue:
            _i12.ifNotNull(
              _i12.dummyValueOrNull<T>(
                this,
                Invocation.method(#exclusively, [action]),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_6<T>(this, Invocation.method(#exclusively, [action])),
        returnValueForMissingStub:
            _i12.ifNotNull(
              _i12.dummyValueOrNull<T>(
                this,
                Invocation.method(#exclusively, [action]),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_6<T>(this, Invocation.method(#exclusively, [action])),
      ) as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i4.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(#batch, [runInBatch]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i4.QueryInterceptor? interceptor,
  }) => (super.noSuchMethod(
    Invocation.method(
      #runWithInterceptor,
      [action],
      {#interceptor: interceptor},
    ),
    returnValue:
        _i12.ifNotNull(
          _i12.dummyValueOrNull<T>(
            this,
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
          ),
          (T v) => _i5.Future<T>.value(v),
        ) ??
        _FakeFuture_6<T>(
          this,
          Invocation.method(
            #runWithInterceptor,
            [action],
            {#interceptor: interceptor},
          ),
        ),
    returnValueForMissingStub:
        _i12.ifNotNull(
          _i12.dummyValueOrNull<T>(
            this,
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
          ),
          (T v) => _i5.Future<T>.value(v),
        ) ??
        _FakeFuture_6<T>(
          this,
          Invocation.method(
            #runWithInterceptor,
            [action],
            {#interceptor: interceptor},
          ),
        ),
  ) as _i5.Future<T>);

  @override
  _i4.GenerationContext $write(
    _i4.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) => (super.noSuchMethod(
    Invocation.method(
      #$write,
      [component],
      {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
    ),
    returnValue: _FakeGenerationContext_5(
      this,
      Invocation.method(
        #$write,
        [component],
        {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
      ),
    ),
    returnValueForMissingStub: _FakeGenerationContext_5(
      this,
      Invocation.method(
        #$write,
        [component],
        {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
      ),
    ),
  ) as _i4.GenerationContext);

  @override
  _i4.GenerationContext $writeInsertable(
    _i4.TableInfo<_i4.Table, dynamic>? table,
    _i4.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) => (super.noSuchMethod(
    Invocation.method(
      #$writeInsertable,
      [table, insertable],
      {#startIndex: startIndex},
    ),
    returnValue: _FakeGenerationContext_5(
      this,
      Invocation.method(
        #$writeInsertable,
        [table, insertable],
        {#startIndex: startIndex},
      ),
    ),
    returnValueForMissingStub: _FakeGenerationContext_5(
      this,
      Invocation.method(
        #$writeInsertable,
        [table, insertable],
        {#startIndex: startIndex},
      ),
    ),
  ) as _i4.GenerationContext);

  @override
  _i4.GenerationContext $writeUpdateInsertable(
    _i4.TableInfo<_i4.Table, dynamic>? table,
    _i4.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) => (super.noSuchMethod(
    Invocation.method(
      #$writeUpdateInsertable,
      [table, insertable],
      {#startIndex: startIndex},
    ),
    returnValue: _FakeGenerationContext_5(
      this,
      Invocation.method(
        #$writeUpdateInsertable,
        [table, insertable],
        {#startIndex: startIndex},
      ),
    ),
    returnValueForMissingStub: _FakeGenerationContext_5(
      this,
      Invocation.method(
        #$writeUpdateInsertable,
        [table, insertable],
        {#startIndex: startIndex},
      ),
    ),
  ) as _i4.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) => (super.noSuchMethod(
    Invocation.method(#$expandVar, [start, amount]),
    returnValue: _i12.dummyValue<String>(
      this,
      Invocation.method(#$expandVar, [start, amount]),
    ),
    returnValueForMissingStub: _i12.dummyValue<String>(
      this,
      Invocation.method(#$expandVar, [start, amount]),
    ),
  ) as String);

  @override
  _i5.Future<void> refresh() => (super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  T? getKey<T extends Object>(String? key) => (super.noSuchMethod(
    Invocation.method(#getKey, [key]),
    returnValueForMissingStub: null,
  ) as T?);

  @override
  void setKey(String? key, Object? value) => super.noSuchMethod(
    Invocation.method(#setKey, [key, value]),
    returnValueForMissingStub: null,
  );

  @override
  void removeKey(String? key) => super.noSuchMethod(
    Invocation.method(#removeKey, [key]),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, Object> getAll([Set<String>? keys]) => (super.noSuchMethod(
    Invocation.method(#getAll, [keys]),
    returnValue: <String, Object>{},
    returnValueForMissingStub: <String, Object>{},
  ) as Map<String, Object>);

  @override
  void setAll(Map<String, Object?>? data) => super.noSuchMethod(
    Invocation.method(#setAll, [data]),
    returnValueForMissingStub: null,
  );

  @override
  void removeAll([Set<String>? keys]) => super.noSuchMethod(
    Invocation.method(#removeAll, [keys]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> didPopRoute() => (super.noSuchMethod(
    Invocation.method(#didPopRoute, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  bool handleStartBackGesture(_i14.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
        Invocation.method(#handleStartBackGesture, [backEvent]),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void handleUpdateBackGestureProgress(_i14.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(#handleUpdateBackGestureProgress, [backEvent]),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCommitBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCancelBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleStatusBarTap() => super.noSuchMethod(
    Invocation.method(#handleStatusBarTap, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> didPushRoute(String? route) => (super.noSuchMethod(
    Invocation.method(#didPushRoute, [route]),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> didPushRouteInformation(
    _i15.RouteInformation? routeInformation,
  ) => (super.noSuchMethod(
    Invocation.method(#didPushRouteInformation, [routeInformation]),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
    Invocation.method(#didChangeMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
    Invocation.method(#didChangeTextScaleFactor, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
    Invocation.method(#didChangePlatformBrightness, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeLocales(List<_i16.Locale>? locales) => super.noSuchMethod(
    Invocation.method(#didChangeLocales, [locales]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAppLifecycleState(_i16.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(#didChangeAppLifecycleState, [state]),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeViewFocus(_i16.ViewFocusEvent? event) => super.noSuchMethod(
    Invocation.method(#didChangeViewFocus, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i16.AppExitResponse> didRequestAppExit() => (super.noSuchMethod(
    Invocation.method(#didRequestAppExit, []),
    returnValue: _i5.Future<_i16.AppExitResponse>.value(
      _i16.AppExitResponse.exit,
    ),
    returnValueForMissingStub: _i5.Future<_i16.AppExitResponse>.value(
      _i16.AppExitResponse.exit,
    ),
  ) as _i5.Future<_i16.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
    Invocation.method(#didHaveMemoryPressure, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
    Invocation.method(#didChangeAccessibilityFeatures, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i9.File {
  @override
  _i9.File get absolute => (super.noSuchMethod(
    Invocation.getter(#absolute),
    returnValue: _FakeFile_30(this, Invocation.getter(#absolute)),
    returnValueForMissingStub: _FakeFile_30(this, Invocation.getter(#absolute)),
  ) as _i9.File);

  @override
  String get path => (super.noSuchMethod(
    Invocation.getter(#path),
    returnValue: _i12.dummyValue<String>(this, Invocation.getter(#path)),
    returnValueForMissingStub: _i12.dummyValue<String>(
      this,
      Invocation.getter(#path),
    ),
  ) as String);

  @override
  Uri get uri => (super.noSuchMethod(
    Invocation.getter(#uri),
    returnValue: _FakeUri_31(this, Invocation.getter(#uri)),
    returnValueForMissingStub: _FakeUri_31(this, Invocation.getter(#uri)),
  ) as Uri);

  @override
  bool get isAbsolute => (super.noSuchMethod(
    Invocation.getter(#isAbsolute),
    returnValue: false,
    returnValueForMissingStub: false,
  ) as bool);

  @override
  _i9.Directory get parent => (super.noSuchMethod(
    Invocation.getter(#parent),
    returnValue: _FakeDirectory_32(this, Invocation.getter(#parent)),
    returnValueForMissingStub: _FakeDirectory_32(
      this,
      Invocation.getter(#parent),
    ),
  ) as _i9.Directory);

  @override
  _i5.Future<_i9.File> create({
    bool? recursive = false,
    bool? exclusive = false,
  }) => (super.noSuchMethod(
    Invocation.method(#create, [], {
      #recursive: recursive,
      #exclusive: exclusive,
    }),
    returnValue: _i5.Future<_i9.File>.value(
      _FakeFile_30(
        this,
        Invocation.method(#create, [], {
          #recursive: recursive,
          #exclusive: exclusive,
        }),
      ),
    ),
    returnValueForMissingStub: _i5.Future<_i9.File>.value(
      _FakeFile_30(
        this,
        Invocation.method(#create, [], {
          #recursive: recursive,
          #exclusive: exclusive,
        }),
      ),
    ),
  ) as _i5.Future<_i9.File>);

  @override
  void createSync({bool? recursive = false, bool? exclusive = false}) =>
      super.noSuchMethod(
        Invocation.method(#createSync, [], {
          #recursive: recursive,
          #exclusive: exclusive,
        }),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i9.File> rename(String? newPath) => (super.noSuchMethod(
    Invocation.method(#rename, [newPath]),
    returnValue: _i5.Future<_i9.File>.value(
      _FakeFile_30(this, Invocation.method(#rename, [newPath])),
    ),
    returnValueForMissingStub: _i5.Future<_i9.File>.value(
      _FakeFile_30(this, Invocation.method(#rename, [newPath])),
    ),
  ) as _i5.Future<_i9.File>);

  @override
  _i9.File renameSync(String? newPath) => (super.noSuchMethod(
    Invocation.method(#renameSync, [newPath]),
    returnValue: _FakeFile_30(this, Invocation.method(#renameSync, [newPath])),
    returnValueForMissingStub: _FakeFile_30(
      this,
      Invocation.method(#renameSync, [newPath]),
    ),
  ) as _i9.File);

  @override
  _i5.Future<_i9.FileSystemEntity> delete({bool? recursive = false}) =>
      (super.noSuchMethod(
        Invocation.method(#delete, [], {#recursive: recursive}),
        returnValue: _i5.Future<_i9.FileSystemEntity>.value(
          _FakeFileSystemEntity_33(
            this,
            Invocation.method(#delete, [], {#recursive: recursive}),
          ),
        ),
        returnValueForMissingStub: _i5.Future<_i9.FileSystemEntity>.value(
          _FakeFileSystemEntity_33(
            this,
            Invocation.method(#delete, [], {#recursive: recursive}),
          ),
        ),
      ) as _i5.Future<_i9.FileSystemEntity>);

  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
    Invocation.method(#deleteSync, [], {#recursive: recursive}),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i9.File> copy(String? newPath) => (super.noSuchMethod(
    Invocation.method(#copy, [newPath]),
    returnValue: _i5.Future<_i9.File>.value(
      _FakeFile_30(this, Invocation.method(#copy, [newPath])),
    ),
    returnValueForMissingStub: _i5.Future<_i9.File>.value(
      _FakeFile_30(this, Invocation.method(#copy, [newPath])),
    ),
  ) as _i5.Future<_i9.File>);

  @override
  _i9.File copySync(String? newPath) => (super.noSuchMethod(
    Invocation.method(#copySync, [newPath]),
    returnValue: _FakeFile_30(this, Invocation.method(#copySync, [newPath])),
    returnValueForMissingStub: _FakeFile_30(
      this,
      Invocation.method(#copySync, [newPath]),
    ),
  ) as _i9.File);

  @override
  _i5.Future<int> length() => (super.noSuchMethod(
    Invocation.method(#length, []),
    returnValue: _i5.Future<int>.value(0),
    returnValueForMissingStub: _i5.Future<int>.value(0),
  ) as _i5.Future<int>);

  @override
  int lengthSync() => (super.noSuchMethod(
    Invocation.method(#lengthSync, []),
    returnValue: 0,
    returnValueForMissingStub: 0,
  ) as int);

  @override
  _i5.Future<DateTime> lastAccessed() => (super.noSuchMethod(
    Invocation.method(#lastAccessed, []),
    returnValue: _i5.Future<DateTime>.value(
      _FakeDateTime_34(this, Invocation.method(#lastAccessed, [])),
    ),
    returnValueForMissingStub: _i5.Future<DateTime>.value(
      _FakeDateTime_34(this, Invocation.method(#lastAccessed, [])),
    ),
  ) as _i5.Future<DateTime>);

  @override
  DateTime lastAccessedSync() => (super.noSuchMethod(
    Invocation.method(#lastAccessedSync, []),
    returnValue: _FakeDateTime_34(
      this,
      Invocation.method(#lastAccessedSync, []),
    ),
    returnValueForMissingStub: _FakeDateTime_34(
      this,
      Invocation.method(#lastAccessedSync, []),
    ),
  ) as DateTime);

  @override
  _i5.Future<dynamic> setLastAccessed(DateTime? time) => (super.noSuchMethod(
    Invocation.method(#setLastAccessed, [time]),
    returnValue: _i5.Future<dynamic>.value(),
    returnValueForMissingStub: _i5.Future<dynamic>.value(),
  ) as _i5.Future<dynamic>);

  @override
  void setLastAccessedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastAccessedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<DateTime> lastModified() => (super.noSuchMethod(
    Invocation.method(#lastModified, []),
    returnValue: _i5.Future<DateTime>.value(
      _FakeDateTime_34(this, Invocation.method(#lastModified, [])),
    ),
    returnValueForMissingStub: _i5.Future<DateTime>.value(
      _FakeDateTime_34(this, Invocation.method(#lastModified, [])),
    ),
  ) as _i5.Future<DateTime>);

  @override
  DateTime lastModifiedSync() => (super.noSuchMethod(
    Invocation.method(#lastModifiedSync, []),
    returnValue: _FakeDateTime_34(
      this,
      Invocation.method(#lastModifiedSync, []),
    ),
    returnValueForMissingStub: _FakeDateTime_34(
      this,
      Invocation.method(#lastModifiedSync, []),
    ),
  ) as DateTime);

  @override
  _i5.Future<dynamic> setLastModified(DateTime? time) => (super.noSuchMethod(
    Invocation.method(#setLastModified, [time]),
    returnValue: _i5.Future<dynamic>.value(),
    returnValueForMissingStub: _i5.Future<dynamic>.value(),
  ) as _i5.Future<dynamic>);

  @override
  void setLastModifiedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastModifiedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i9.RandomAccessFile> open({
    _i9.FileMode? mode = _i9.FileMode.read,
  }) => (super.noSuchMethod(
    Invocation.method(#open, [], {#mode: mode}),
    returnValue: _i5.Future<_i9.RandomAccessFile>.value(
      _FakeRandomAccessFile_35(
        this,
        Invocation.method(#open, [], {#mode: mode}),
      ),
    ),
    returnValueForMissingStub: _i5.Future<_i9.RandomAccessFile>.value(
      _FakeRandomAccessFile_35(
        this,
        Invocation.method(#open, [], {#mode: mode}),
      ),
    ),
  ) as _i5.Future<_i9.RandomAccessFile>);

  @override
  _i9.RandomAccessFile openSync({_i9.FileMode? mode = _i9.FileMode.read}) =>
      (super.noSuchMethod(
        Invocation.method(#openSync, [], {#mode: mode}),
        returnValue: _FakeRandomAccessFile_35(
          this,
          Invocation.method(#openSync, [], {#mode: mode}),
        ),
        returnValueForMissingStub: _FakeRandomAccessFile_35(
          this,
          Invocation.method(#openSync, [], {#mode: mode}),
        ),
      ) as _i9.RandomAccessFile);

  @override
  _i5.Stream<List<int>> openRead([int? start, int? end]) => (super.noSuchMethod(
    Invocation.method(#openRead, [start, end]),
    returnValue: _i5.Stream<List<int>>.empty(),
    returnValueForMissingStub: _i5.Stream<List<int>>.empty(),
  ) as _i5.Stream<List<int>>);

  @override
  _i9.IOSink openWrite({
    _i9.FileMode? mode = _i9.FileMode.write,
    _i17.Encoding? encoding = const _i17.Utf8Codec(),
  }) => (super.noSuchMethod(
    Invocation.method(#openWrite, [], {#mode: mode, #encoding: encoding}),
    returnValue: _FakeIOSink_36(
      this,
      Invocation.method(#openWrite, [], {#mode: mode, #encoding: encoding}),
    ),
    returnValueForMissingStub: _FakeIOSink_36(
      this,
      Invocation.method(#openWrite, [], {#mode: mode, #encoding: encoding}),
    ),
  ) as _i9.IOSink);

  @override
  _i5.Future<_i18.Uint8List> readAsBytes() => (super.noSuchMethod(
    Invocation.method(#readAsBytes, []),
    returnValue: _i5.Future<_i18.Uint8List>.value(_i18.Uint8List(0)),
    returnValueForMissingStub: _i5.Future<_i18.Uint8List>.value(
      _i18.Uint8List(0),
    ),
  ) as _i5.Future<_i18.Uint8List>);

  @override
  _i18.Uint8List readAsBytesSync() => (super.noSuchMethod(
    Invocation.method(#readAsBytesSync, []),
    returnValue: _i18.Uint8List(0),
    returnValueForMissingStub: _i18.Uint8List(0),
  ) as _i18.Uint8List);

  @override
  _i5.Future<String> readAsString({
    _i17.Encoding? encoding = const _i17.Utf8Codec(),
  }) => (super.noSuchMethod(
    Invocation.method(#readAsString, [], {#encoding: encoding}),
    returnValue: _i5.Future<String>.value(
      _i12.dummyValue<String>(
        this,
        Invocation.method(#readAsString, [], {#encoding: encoding}),
      ),
    ),
    returnValueForMissingStub: _i5.Future<String>.value(
      _i12.dummyValue<String>(
        this,
        Invocation.method(#readAsString, [], {#encoding: encoding}),
      ),
    ),
  ) as _i5.Future<String>);

  @override
  String readAsStringSync({_i17.Encoding? encoding = const _i17.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
        ),
      ) as String);

  @override
  _i5.Future<List<String>> readAsLines({
    _i17.Encoding? encoding = const _i17.Utf8Codec(),
  }) => (super.noSuchMethod(
    Invocation.method(#readAsLines, [], {#encoding: encoding}),
    returnValue: _i5.Future<List<String>>.value(<String>[]),
    returnValueForMissingStub: _i5.Future<List<String>>.value(<String>[]),
  ) as _i5.Future<List<String>>);

  @override
  List<String> readAsLinesSync({
    _i17.Encoding? encoding = const _i17.Utf8Codec(),
  }) => (super.noSuchMethod(
    Invocation.method(#readAsLinesSync, [], {#encoding: encoding}),
    returnValue: <String>[],
    returnValueForMissingStub: <String>[],
  ) as List<String>);

  @override
  _i5.Future<_i9.File> writeAsBytes(
    List<int>? bytes, {
    _i9.FileMode? mode = _i9.FileMode.write,
    bool? flush = false,
  }) => (super.noSuchMethod(
    Invocation.method(#writeAsBytes, [bytes], {#mode: mode, #flush: flush}),
    returnValue: _i5.Future<_i9.File>.value(
      _FakeFile_30(
        this,
        Invocation.method(#writeAsBytes, [bytes], {#mode: mode, #flush: flush}),
      ),
    ),
    returnValueForMissingStub: _i5.Future<_i9.File>.value(
      _FakeFile_30(
        this,
        Invocation.method(#writeAsBytes, [bytes], {#mode: mode, #flush: flush}),
      ),
    ),
  ) as _i5.Future<_i9.File>);

  @override
  void writeAsBytesSync(
    List<int>? bytes, {
    _i9.FileMode? mode = _i9.FileMode.write,
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(#writeAsBytesSync, [bytes], {#mode: mode, #flush: flush}),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i9.File> writeAsString(
    String? contents, {
    _i9.FileMode? mode = _i9.FileMode.write,
    _i17.Encoding? encoding = const _i17.Utf8Codec(),
    bool? flush = false,
  }) => (super.noSuchMethod(
    Invocation.method(
      #writeAsString,
      [contents],
      {#mode: mode, #encoding: encoding, #flush: flush},
    ),
    returnValue: _i5.Future<_i9.File>.value(
      _FakeFile_30(
        this,
        Invocation.method(
          #writeAsString,
          [contents],
          {#mode: mode, #encoding: encoding, #flush: flush},
        ),
      ),
    ),
    returnValueForMissingStub: _i5.Future<_i9.File>.value(
      _FakeFile_30(
        this,
        Invocation.method(
          #writeAsString,
          [contents],
          {#mode: mode, #encoding: encoding, #flush: flush},
        ),
      ),
    ),
  ) as _i5.Future<_i9.File>);

  @override
  void writeAsStringSync(
    String? contents, {
    _i9.FileMode? mode = _i9.FileMode.write,
    _i17.Encoding? encoding = const _i17.Utf8Codec(),
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeAsStringSync,
      [contents],
      {#mode: mode, #encoding: encoding, #flush: flush},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> exists() => (super.noSuchMethod(
    Invocation.method(#exists, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  bool existsSync() => (super.noSuchMethod(
    Invocation.method(#existsSync, []),
    returnValue: false,
    returnValueForMissingStub: false,
  ) as bool);

  @override
  _i5.Future<String> resolveSymbolicLinks() => (super.noSuchMethod(
    Invocation.method(#resolveSymbolicLinks, []),
    returnValue: _i5.Future<String>.value(
      _i12.dummyValue<String>(
        this,
        Invocation.method(#resolveSymbolicLinks, []),
      ),
    ),
    returnValueForMissingStub: _i5.Future<String>.value(
      _i12.dummyValue<String>(
        this,
        Invocation.method(#resolveSymbolicLinks, []),
      ),
    ),
  ) as _i5.Future<String>);

  @override
  String resolveSymbolicLinksSync() => (super.noSuchMethod(
    Invocation.method(#resolveSymbolicLinksSync, []),
    returnValue: _i12.dummyValue<String>(
      this,
      Invocation.method(#resolveSymbolicLinksSync, []),
    ),
    returnValueForMissingStub: _i12.dummyValue<String>(
      this,
      Invocation.method(#resolveSymbolicLinksSync, []),
    ),
  ) as String);

  @override
  _i5.Future<_i9.FileStat> stat() => (super.noSuchMethod(
    Invocation.method(#stat, []),
    returnValue: _i5.Future<_i9.FileStat>.value(
      _FakeFileStat_37(this, Invocation.method(#stat, [])),
    ),
    returnValueForMissingStub: _i5.Future<_i9.FileStat>.value(
      _FakeFileStat_37(this, Invocation.method(#stat, [])),
    ),
  ) as _i5.Future<_i9.FileStat>);

  @override
  _i9.FileStat statSync() => (super.noSuchMethod(
    Invocation.method(#statSync, []),
    returnValue: _FakeFileStat_37(this, Invocation.method(#statSync, [])),
    returnValueForMissingStub: _FakeFileStat_37(
      this,
      Invocation.method(#statSync, []),
    ),
  ) as _i9.FileStat);

  @override
  _i5.Stream<_i9.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) => (super.noSuchMethod(
    Invocation.method(#watch, [], {#events: events, #recursive: recursive}),
    returnValue: _i5.Stream<_i9.FileSystemEvent>.empty(),
    returnValueForMissingStub: _i5.Stream<_i9.FileSystemEvent>.empty(),
  ) as _i5.Stream<_i9.FileSystemEvent>);
}

/// A class which mocks [AuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepository extends _i1.Mock
    implements _i19.AuthenticationRepository {
  @override
  _i5.Future<_i20.User> getUser() => (super.noSuchMethod(
    Invocation.method(#getUser, []),
    returnValue: _i5.Future<_i20.User>.value(
      _i12.dummyValue<_i20.User>(this, Invocation.method(#getUser, [])),
    ),
    returnValueForMissingStub: _i5.Future<_i20.User>.value(
      _i12.dummyValue<_i20.User>(this, Invocation.method(#getUser, [])),
    ),
  ) as _i5.Future<_i20.User>);

  @override
  _i5.Stream<_i20.User> userChanges() => (super.noSuchMethod(
    Invocation.method(#userChanges, []),
    returnValue: _i5.Stream<_i20.User>.empty(),
    returnValueForMissingStub: _i5.Stream<_i20.User>.empty(),
  ) as _i5.Stream<_i20.User>);

  @override
  _i5.Future<_i20.User> signIn(_i21.SignInData? data) => (super.noSuchMethod(
    Invocation.method(#signIn, [data]),
    returnValue: _i5.Future<_i20.User>.value(
      _i12.dummyValue<_i20.User>(this, Invocation.method(#signIn, [data])),
    ),
    returnValueForMissingStub: _i5.Future<_i20.User>.value(
      _i12.dummyValue<_i20.User>(this, Invocation.method(#signIn, [data])),
    ),
  ) as _i5.Future<_i20.User>);

  @override
  _i5.Future<_i20.User?> restore() => (super.noSuchMethod(
    Invocation.method(#restore, []),
    returnValue: _i5.Future<_i20.User?>.value(),
    returnValueForMissingStub: _i5.Future<_i20.User?>.value(),
  ) as _i5.Future<_i20.User?>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
    Invocation.method(#signOut, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i22.SettingsRepository {
  @override
  _i5.Future<_i23.AppSettings> readSettings({String? userID}) =>
      (super.noSuchMethod(
        Invocation.method(#readSettings, [], {#userID: userID}),
        returnValue: _i5.Future<_i23.AppSettings>.value(
          _i12.dummyValue<_i23.AppSettings>(
            this,
            Invocation.method(#readSettings, [], {#userID: userID}),
          ),
        ),
        returnValueForMissingStub: _i5.Future<_i23.AppSettings>.value(
          _i12.dummyValue<_i23.AppSettings>(
            this,
            Invocation.method(#readSettings, [], {#userID: userID}),
          ),
        ),
      ) as _i5.Future<_i23.AppSettings>);

  @override
  _i5.Future<void> saveSettings({
    required _i23.AppSettings? settings,
    String? userID,
  }) => (super.noSuchMethod(
    Invocation.method(#saveSettings, [], {
      #settings: settings,
      #userID: userID,
    }),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<_i24.UserPreferences> readPreferences() => (super.noSuchMethod(
    Invocation.method(#readPreferences, []),
    returnValue: _i5.Future<_i24.UserPreferences>.value(
      _i12.dummyValue<_i24.UserPreferences>(
        this,
        Invocation.method(#readPreferences, []),
      ),
    ),
    returnValueForMissingStub: _i5.Future<_i24.UserPreferences>.value(
      _i12.dummyValue<_i24.UserPreferences>(
        this,
        Invocation.method(#readPreferences, []),
      ),
    ),
  ) as _i5.Future<_i24.UserPreferences>);

  @override
  _i5.Future<void> savePreferences(_i24.UserPreferences? preferences) =>
      (super.noSuchMethod(
        Invocation.method(#savePreferences, [preferences]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AppSettingsDataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSettingsDataProvider extends _i1.Mock
    implements _i25.AppSettingsDataProvider {
  @override
  _i10.SharedPreferencesAsync get sharedPreferences => (super.noSuchMethod(
    Invocation.getter(#sharedPreferences),
    returnValue: _FakeSharedPreferencesAsync_38(
      this,
      Invocation.getter(#sharedPreferences),
    ),
    returnValueForMissingStub: _FakeSharedPreferencesAsync_38(
      this,
      Invocation.getter(#sharedPreferences),
    ),
  ) as _i10.SharedPreferencesAsync);

  @override
  _i26.AppSettingsCodec get codec => (super.noSuchMethod(
    Invocation.getter(#codec),
    returnValue: _i12.dummyValue<_i26.AppSettingsCodec>(
      this,
      Invocation.getter(#codec),
    ),
    returnValueForMissingStub: _i12.dummyValue<_i26.AppSettingsCodec>(
      this,
      Invocation.getter(#codec),
    ),
  ) as _i26.AppSettingsCodec);

  @override
  _i5.Future<_i23.AppSettings> read({String? userID}) => (super.noSuchMethod(
    Invocation.method(#read, [], {#userID: userID}),
    returnValue: _i5.Future<_i23.AppSettings>.value(
      _i12.dummyValue<_i23.AppSettings>(
        this,
        Invocation.method(#read, [], {#userID: userID}),
      ),
    ),
    returnValueForMissingStub: _i5.Future<_i23.AppSettings>.value(
      _i12.dummyValue<_i23.AppSettings>(
        this,
        Invocation.method(#read, [], {#userID: userID}),
      ),
    ),
  ) as _i5.Future<_i23.AppSettings>);

  @override
  _i5.Future<void> save({
    required _i23.AppSettings? settings,
    String? userID,
  }) => (super.noSuchMethod(
    Invocation.method(#save, [], {#settings: settings, #userID: userID}),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);
}

/// A class which mocks [UserPreferencesDataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserPreferencesDataProvider extends _i1.Mock
    implements _i27.UserPreferencesDataProvider {
  @override
  _i10.SharedPreferencesAsync get sharedPreferences => (super.noSuchMethod(
    Invocation.getter(#sharedPreferences),
    returnValue: _FakeSharedPreferencesAsync_38(
      this,
      Invocation.getter(#sharedPreferences),
    ),
    returnValueForMissingStub: _FakeSharedPreferencesAsync_38(
      this,
      Invocation.getter(#sharedPreferences),
    ),
  ) as _i10.SharedPreferencesAsync);

  @override
  _i28.UserPreferencesCodec get codec => (super.noSuchMethod(
    Invocation.getter(#codec),
    returnValue: _i12.dummyValue<_i28.UserPreferencesCodec>(
      this,
      Invocation.getter(#codec),
    ),
    returnValueForMissingStub: _i12.dummyValue<_i28.UserPreferencesCodec>(
      this,
      Invocation.getter(#codec),
    ),
  ) as _i28.UserPreferencesCodec);

  @override
  _i5.Future<_i24.UserPreferences> read() => (super.noSuchMethod(
    Invocation.method(#read, []),
    returnValue: _i5.Future<_i24.UserPreferences>.value(
      _i12.dummyValue<_i24.UserPreferences>(this, Invocation.method(#read, [])),
    ),
    returnValueForMissingStub: _i5.Future<_i24.UserPreferences>.value(
      _i12.dummyValue<_i24.UserPreferences>(this, Invocation.method(#read, [])),
    ),
  ) as _i5.Future<_i24.UserPreferences>);

  @override
  _i5.Future<void> save(_i24.UserPreferences? preferences) =>
      (super.noSuchMethod(
        Invocation.method(#save, [preferences]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
