name: ui
description: Shared UI Components, Widgets, Fonts, Colors and Theme
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.13.2 <4.0.0'
  flutter: ">=3.47.2"

# https://dart.dev/tools/pub/workspaces
resolution: workspace

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # UI and image cropping
  extended_image: ^10.1.0
  cupertino_icons: ^1.0.9
  rive: ^0.14.11
  flutter_svg: ^2.3.0
  flutter_slidable: ^4.0.3

  # Utility
  cross_file: ^0.3.5+4
  platform_info: ^5.0.0
  meta: any
  collection: any
  # google_fonts: any

dev_dependencies:
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter
  # Integration tests for Flutter
  integration_test:
    sdk: flutter

  # Testing
  test: any

  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/check_error.riv

  # fonts:
  # - family: icomoon
  #   fonts:
  #     - asset: packages/ui/fonts/icomoon.ttf

  shaders:
    - lib/shaders/shimmer.frag
